[package]
name = "ramtool"
version = "0.1.0"
edition = "2021"
description = "Unpack and repack Android boot/init_boot ramdisk images"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive"] }
flate2 = { version = "1", default-features = false, features = ["rust_backend"] }
goblin = { version = "0.10", default-features = false, features = ["std", "elf32", "elf64", "endian_fd"] }
lz4_flex = { version = "0.14", default-features = false, features = ["std", "frame"] }

[profile.release]
strip = true
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
